import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { QueryClientProvider, QueryClient } from '@tanstack/react-query';
import Providers from '@/components/ui/Providers';
import Header from '@/components/ui/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
